name: clax
description: A shopping app sample that uses Provider for state management.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Essential Pacakges
  http: ^0.12.0+4
  dbcrypt: ^1.0.0
  provider: ^4.0.2
  url_launcher: ^5.4.2
  webview_flutter: ^0.3.19+9
  shared_preferences: ^0.5.6+3

  # UI Packages
  pin_view: ^1.0.1
  select_dialog: 1.0.7
  contact_picker: ^0.0.2
  overlay_support: ^1.0.4
  flutter_spinkit: ^4.1.2
  month_picker_dialog: ^0.3.1
  font_awesome_flutter: ^8.7.0

  # Google  Services
  geocoder: ^0.2.1
  geolocator: ^5.3.0
  firebase_database: ^3.1.5
  google_maps_utils: ^1.2.1+1
  firebase_messaging: ^6.0.13
  google_maps_flutter: ^0.5.24+3
  google_maps_webservice: ^0.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Extralight.ttf
          weight: 100
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Semibold.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 600

    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 500
